// SPDX-License-Identifier: BUSL-1.1

//! [`ReplicatedEntry`] — the routing envelope carried alongside a
//! [`super::ReplicatedWrite`] on the Raft log, plus its (de)serialization.

use super::replicated_write::ReplicatedWrite;
use super::transaction_redo_wire::ReplicatedEventSource;

/// Metadata carried alongside the write for routing on the receiving node.
#[derive(
    Debug,
    Clone,
    serde::Serialize,
    serde::Deserialize,
    zerompk::ToMessagePack,
    zerompk::FromMessagePack,
)]
pub struct ReplicatedEntry {
    pub tenant_id: u64,
    /// Database scope for the write. `0` decodes to `DatabaseId::DEFAULT`.
    #[serde(default)]
    pub database_id: u64,
    pub vshard_id: u32,
    /// Per-proposal idempotency key. Generated by the proposer when the
    /// entry is constructed and embedded in the Raft log payload so the
    /// apply path can match the entry that actually committed at a given
    /// `(group_id, log_index)` against the entry the proposer is waiting
    /// for. A mismatch means a leader change overwrote the proposer's
    /// reservation with a different proposer's entry — the apply path
    /// surfaces `RetryableLeaderChange` so the gateway re-proposes.
    ///
    /// Zero is reserved as "no key" (synthetic entries and entries without
    /// the field). The tracker treats `0` as a wildcard.
    pub idempotency_key: u64,
    pub write: ReplicatedWrite,
    /// HLC wall time, in nanoseconds, at which the proposer committed to the
    /// write. Stamped once before the first propose, so a re-proposal keeps
    /// it. Every replica records it as the write's instant on the tenant's
    /// observed write high-water, however late it applies. `0` for an entry
    /// proposed without one; its apply stamps the instant of its own append.
    pub write_hlc: u64,
    /// The metadata-group index the proposer had applied when it proposed
    /// the write. Every replica applies the write only once its own metadata
    /// apply reached this index, so the write never lands against an older
    /// catalog than the one it was planned against: a same-name collection's
    /// pending purge has reclaimed its storage, and the collection the write
    /// targets is registered. `0` for an entry proposed without one.
    pub metadata_floor: u64,
    /// The source every replica stamps on the write's events. It decides
    /// whether AFTER triggers fire, on every replica alike.
    pub event_source: ReplicatedEventSource,
    /// The RESTORE that re-issued the write, `0` for any other write. Every
    /// replica raises the write's tenant mark under this id, so a retry of the
    /// same restore knows the write as its own.
    pub restore_id: u64,
    /// Every user collection the write names, with the incarnation its
    /// proposer planned against. A replica applies the write only while each
    /// collection still holds that incarnation.
    pub incarnations: Vec<CollectionIncarnation>,
}

/// A user collection a replicated write names, and the incarnation its
/// proposer planned against. `Hlc::ZERO` when the proposer's catalog held no
/// incarnation for it.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    zerompk::ToMessagePack,
    zerompk::FromMessagePack,
)]
pub struct CollectionIncarnation {
    /// The collection as the write's plan names it: database-qualified
    /// outside the default database.
    pub collection: String,
    pub incarnation: nodedb_types::Hlc,
}

impl ReplicatedEntry {
    /// Construct a new `ReplicatedEntry` with a freshly generated
    /// idempotency key. All production write paths go through this
    /// constructor; only deserialized log entries skip it (the key is
    /// preserved through `from_bytes`).
    pub fn new(tenant_id: u64, database_id: u64, vshard_id: u32, write: ReplicatedWrite) -> Self {
        // OR with 1 so the LSB is set: zero is reserved as the "no key"
        // sentinel and a fresh `rand::random::<u64>()` can in principle
        // hit zero (P ~= 2^-64 but cheap to make impossible).
        let idempotency_key = rand::random::<u64>() | 1;
        Self {
            tenant_id,
            database_id,
            vshard_id,
            idempotency_key,
            write,
            write_hlc: 0,
            metadata_floor: 0,
            event_source: ReplicatedEventSource::User,
            restore_id: 0,
            incarnations: Vec::new(),
        }
    }

    /// Stamp the source every replica gives the write's events.
    pub fn with_event_source(mut self, source: crate::event::EventSource) -> Self {
        self.event_source = ReplicatedEventSource::from(source);
        self
    }

    /// Stamp the RESTORE that re-issued the write.
    pub fn with_restore_id(mut self, restore_id: u64) -> Self {
        self.restore_id = restore_id;
        self
    }

    /// Name the user collections the write targets, as its plan names them.
    /// The proposer stamps each one's incarnation before it proposes.
    pub fn naming<'n>(mut self, collections: impl IntoIterator<Item = &'n str>) -> Self {
        self.incarnations = collections
            .into_iter()
            .map(|collection| CollectionIncarnation {
                collection: collection.to_owned(),
                incarnation: nodedb_types::Hlc::ZERO,
            })
            .collect();
        self
    }

    /// Serialize to bytes for Raft log entry data.
    pub fn encode(&self) -> crate::Result<Vec<u8>> {
        zerompk::to_msgpack_vec(self).map_err(|e| crate::Error::Serialization {
            format: "msgpack".into(),
            detail: format!(
                "replicated entry for vshard {} (tenant {}, database {}): {e}",
                self.vshard_id, self.tenant_id, self.database_id
            ),
        })
    }

    /// [`Self::encode`] for unit tests, which build only encodable entries.
    #[cfg(test)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.encode().expect("encode a test ReplicatedEntry")
    }

    /// Deserialize from Raft log entry data bytes. Bytes of any other shape
    /// return `None`.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        zerompk::from_msgpack::<Self>(data).ok()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bridge::envelope::PhysicalPlan;
    use crate::control::wal_replication::decode;
    use crate::types::{DatabaseId, TenantId, VShardId};
    use nodedb_physical::physical_plan::DocumentOp;
    use nodedb_types::{QualifiedCollection, Surrogate};

    /// Decide + encode in one call, so each test names only the plan it encodes.
    fn to_replicated_entry(
        tenant_id: TenantId,
        database_id: DatabaseId,
        vshard_id: VShardId,
        plan: &PhysicalPlan,
    ) -> crate::Result<Option<ReplicatedEntry>> {
        let write = crate::control::wal_replication::ReplicableWrite::decide_for_replication(plan)?;
        crate::control::wal_replication::encode::to_replicated_entry(
            tenant_id,
            database_id,
            vshard_id,
            &write,
        )
    }

    #[test]
    fn replicated_entry_roundtrip() {
        let entry = ReplicatedEntry::new(
            1,
            0,
            42,
            ReplicatedWrite::PointPut {
                collection: "users".into(),
                document_id: "u1".into(),
                value: b"alice".to_vec(),
                surrogate: 1,
                resolved_sum_targets: Vec::new(),
                resolved_sum_target_bindings: Vec::new(),
                returning: None,
                rls_filters: Vec::new(),
            },
        );
        let original_key = entry.idempotency_key;
        assert_ne!(original_key, 0, "idempotency_key must be non-zero");

        let bytes = entry.to_bytes();
        let decoded = ReplicatedEntry::from_bytes(&bytes).unwrap();
        assert_eq!(decoded.tenant_id, 1);
        assert_eq!(decoded.vshard_id, 42);
        assert_eq!(
            decoded.idempotency_key, original_key,
            "idempotency_key roundtrip"
        );
        match decoded.write {
            ReplicatedWrite::PointPut {
                collection,
                document_id,
                value,
                surrogate,
                resolved_sum_targets,
                resolved_sum_target_bindings,
                returning,
                rls_filters,
            } => {
                assert_eq!(collection, "users");
                assert_eq!(document_id, "u1");
                assert_eq!(value, b"alice");
                assert_eq!(surrogate, 1);
                assert!(resolved_sum_targets.is_empty());
                assert!(resolved_sum_target_bindings.is_empty());
                assert_eq!(returning, None);
                assert!(rls_filters.is_empty());
            }
            other => panic!("expected PointPut, got {other:?}"),
        }
    }

    #[test]
    fn the_event_source_roundtrips_and_defaults_to_user() {
        let write = ReplicatedWrite::CutBarrier {
            hlc: 7,
            restore_point: 0,
            capture: None,
        };
        let plain = ReplicatedEntry::new(1, 0, 3, write.clone());
        assert_eq!(plain.event_source, ReplicatedEventSource::User);

        let restored = ReplicatedEntry::new(1, 0, 3, write)
            .with_event_source(crate::event::EventSource::Restore);
        let decoded = ReplicatedEntry::from_bytes(&restored.to_bytes()).expect("decode");
        assert_eq!(decoded.event_source, ReplicatedEventSource::Restore);
        assert_eq!(
            crate::event::EventSource::from(decoded.event_source),
            crate::event::EventSource::Restore
        );
    }

    #[test]
    fn non_default_database_id_roundtrips_through_encode_decode() {
        let tenant = TenantId::new(1);
        let database = DatabaseId::new(1024);
        let vshard = VShardId::new(0);

        let plan = PhysicalPlan::Document(DocumentOp::PointPut {
            collection: QualifiedCollection::new(DatabaseId::DEFAULT, "c"),
            document_id: "d".into(),
            value: vec![1, 2, 3],
            surrogate: Surrogate::new(1),
            pk_bytes: Vec::new(),
            returning: None,
            rls_filters: Vec::new(),
            resolved_sum_targets: Vec::new(),
        });

        let entry = to_replicated_entry(tenant, database, vshard, &plan)
            .expect("encode must not error")
            .expect("PointPut should produce a ReplicatedEntry");
        assert_eq!(entry.database_id, database.as_u64());

        let bytes = entry.to_bytes();
        let decoded_entry = ReplicatedEntry::from_bytes(&bytes).expect("decode failed");
        assert_eq!(
            decoded_entry.database_id,
            database.as_u64(),
            "database_id must survive the byte round-trip"
        );

        let (_, _, decoded_plan, _) = decode::decode_replicated_entry(&bytes)
            .expect("decode_replicated_entry error")
            .expect("decode_replicated_entry returned None");
        match decoded_plan {
            PhysicalPlan::Document(DocumentOp::PointPut { collection, .. }) => {
                assert_eq!(collection.as_str(), "c");
            }
            other => panic!("expected Document(PointPut), got {other:?}"),
        }
    }
}
